### ISSUE TITLE
proje yayına alındıktan sonra güncelleme

### ISSUE THREAD

**Issue by serdardurbaris** [barissaslan/django-projesini-yayina-alma#1]
makale için teşekkürler oldukça açıklayıcı ve başarılı fakat kafama takılan ve henüz çözemediğin bir durum sözkonusu. Yayına alınan ve çalıştırılan bir projede sunucuyu reboot etmeden eklenen yada değiştirilen dosyalar (setting.py, static dosylar, view dosyaları) nasıl güncellenir.

**Comment by barissaslan** [comment]
Sunucuyu yeniden başlatmadan değiştirilen dosyalardan haberdar olmasını sağlayamazsanız. Yaptığınız değişikliklerden sonra Nginx'i veya Gunicorn'u (değişikliğe göre değişir) yeniden başlatmanız gerek.
