### ISSUE TITLE
413 request entity too large

### ISSUE THREAD

**Issue by Brali11** [barissaslan/django-projesini-yayina-alma#3]
Web siteme resim yuklerken 413 request entity too large hatasi aliyorum.Bunun sebebinin nginx in ayarlarinda oldugunu dusunuyorum.Bu problemi cozebilmem icin yardim edebilecek olan var mi?

**Comment by barissaslan** [comment]
Sanırım yüklemeye çalıştığınız dosya boyutu, Nginx'in varsayılan maksimum dosya boyutu limitini aşıyor. Nginx konfigürasyon dosyasındaki server bloğuna şu satırı ekleyerek istemciden gelebilecek maksimum dosya boyutunu arttırabilirsiniz:

server {
    client_max_body_size 100M;
    ...
}
